// Package misc provides miscellaneous utility data for the translator.
package misc

// MimeTypes is a comprehensive map of file extensions to their corresponding MIME types.
var MimeTypes = map[string]string{
	"ez":          "application/andrew-inset",
	"aw":          "application/applixware",
	"atom":        "application/atom+xml",
	"atomcat":     "application/atomcat+xml",
	"atomsvc":     "application/atomsvc+xml",
	"bin":         "application/octet-stream",
	"pdf":         "application/pdf",
	"js":          "application/javascript",
	"json":        "application/json",
	"xml":         "application/xml",
	"zip":         "application/zip",
	"gz":          "application/gzip",
	"tar":         "application/x-tar",
	"rar":         "application/x-rar-compressed",
	"7z":          "application/x-7z-compressed",
	"doc":         "application/msword",
	"docx":        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	"xls":         "application/vnd.ms-excel",
	"xlsx":        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	"ppt":         "application/vnd.ms-powerpoint",
	"pptx":        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
	"odt":         "application/vnd.oasis.opendocument.text",
	"ods":         "application/vnd.oasis.opendocument.spreadsheet",
	"odp":         "application/vnd.oasis.opendocument.presentation",
	"epub":        "application/epub+zip",
	"rtf":         "application/rtf",

	// Audio
	"mp3":  "audio/mpeg",
	"wav":  "audio/x-wav",
	"ogg":  "audio/ogg",
	"m4a":  "audio/mp4",
	"flac": "audio/x-flac",
	"aac":  "audio/aac",
	"wma":  "audio/x-ms-wma",

	// Video
	"mp4":  "video/mp4",
	"mpeg": "video/mpeg",
	"avi":  "video/x-msvideo",
	"wmv":  "video/x-ms-wmv",
	"mov":  "video/quicktime",
	"flv":  "video/x-flv",
	"webm": "video/webm",
	"mkv":  "video/x-matroska",
	"3gp":  "video/3gpp",

	// Images
	"jpg":  "image/jpeg",
	"jpeg": "image/jpeg",
	"png":  "image/png",
	"gif":  "image/gif",
	"bmp":  "image/bmp",
	"webp": "image/webp",
	"svg":  "image/svg+xml",
	"ico":  "image/x-icon",
	"tiff": "image/tiff",
	"tif":  "image/tiff",
	"heic": "image/heic",
	"heif": "image/heif",

	// Text
	"txt":  "text/plain",
	"html": "text/html",
	"htm":  "text/html",
	"css":  "text/css",
	"csv":  "text/csv",
	"md":   "text/markdown",
	"yaml": "text/yaml",
	"yml":  "text/yaml",

	// Code
	"go":    "text/x-go",
	"py":    "text/x-python",
	"java":  "text/x-java-source",
	"c":     "text/x-c",
	"cpp":   "text/x-c++",
	"h":     "text/x-c",
	"hpp":   "text/x-c++",
	"rs":    "text/x-rust",
	"ts":    "text/typescript",
	"tsx":   "text/typescript-jsx",
	"jsx":   "text/jsx",
	"rb":    "text/x-ruby",
	"php":   "text/x-php",
	"swift": "text/x-swift",
	"kt":    "text/x-kotlin",
	"scala": "text/x-scala",
	"sh":    "application/x-sh",
	"bash":  "application/x-sh",
	"ps1":   "application/x-powershell",
	"sql":   "application/x-sql",

	// Fonts
	"ttf":   "font/ttf",
	"otf":   "font/otf",
	"woff":  "font/woff",
	"woff2": "font/woff2",
	"eot":   "application/vnd.ms-fontobject",
}
