// Package util provides MIME type mappings for file operations.
package util

// MimeTypes is a comprehensive map of file extensions to their corresponding MIME types.
var MimeTypes = map[string]string{
	"ez":          "application/andrew-inset",
	"aw":          "application/applixware",
	"atom":        "application/atom+xml",
	"atomcat":     "application/atomcat+xml",
	"atomsvc":     "application/atomsvc+xml",
	"ccxml":       "application/ccxml+xml",
	"epub":        "application/epub+zip",
	"jar":         "application/java-archive",
	"class":       "application/java-vm",
	"js":          "application/javascript",
	"json":        "application/json",
	"jsonml":      "application/jsonml+json",
	"doc":         "application/msword",
	"bin":         "application/octet-stream",
	"pdf":         "application/pdf",
	"rtf":         "application/rtf",
	"zip":         "application/zip",
	"gz":          "application/gzip",
	"tar":         "application/x-tar",
	"rar":         "application/x-rar-compressed",
	"7z":          "application/x-7z-compressed",
	"sh":          "application/x-sh",
	"sql":         "application/x-sql",
	"xml":         "application/xml",
	"xhtml":       "application/xhtml+xml",
	"xls":         "application/vnd.ms-excel",
	"xlsx":        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	"ppt":         "application/vnd.ms-powerpoint",
	"pptx":        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
	"docx":        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",

	// Audio
	"mp3":  "audio/mpeg",
	"ogg":  "audio/ogg",
	"wav":  "audio/x-wav",
	"flac": "audio/x-flac",
	"aac":  "audio/x-aac",
	"m4a":  "audio/mp4",
	"wma":  "audio/x-ms-wma",

	// Images
	"bmp":  "image/bmp",
	"gif":  "image/gif",
	"jpg":  "image/jpeg",
	"jpeg": "image/jpeg",
	"png":  "image/png",
	"svg":  "image/svg+xml",
	"tiff": "image/tiff",
	"tif":  "image/tiff",
	"webp": "image/webp",
	"ico":  "image/x-icon",
	"psd":  "image/vnd.adobe.photoshop",

	// Text
	"css":  "text/css",
	"csv":  "text/csv",
	"html": "text/html",
	"htm":  "text/html",
	"txt":  "text/plain",
	"md":   "text/markdown",
	"yaml": "text/yaml",
	"yml":  "text/yaml",

	// Video
	"mp4":  "video/mp4",
	"mpeg": "video/mpeg",
	"mpg":  "video/mpeg",
	"ogv":  "video/ogg",
	"webm": "video/webm",
	"avi":  "video/x-msvideo",
	"mov":  "video/quicktime",
	"mkv":  "video/x-matroska",
	"wmv":  "video/x-ms-wmv",
	"flv":  "video/x-flv",

	// Programming languages
	"c":    "text/x-c",
	"cpp":  "text/x-c",
	"h":    "text/x-c",
	"hpp":  "text/x-c",
	"java": "text/x-java-source",
	"py":   "text/x-python",
	"rb":   "text/x-ruby",
	"go":   "text/x-go",
	"rs":   "text/x-rust",
	"ts":   "text/typescript",
	"tsx":  "text/typescript",
	"jsx":  "text/javascript",

	// Fonts
	"otf":   "font/otf",
	"ttf":   "font/ttf",
	"woff":  "font/woff",
	"woff2": "font/woff2",
}
